#!/bin/bash

# Install kubeadm

# Disable firewall

systemctl stop firewalld
systemctl disable firewalld

cat <<EOF > /etc/yum.repos.d/kubernetes.repo
[kubernetes]
name=Kubernetes
baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
enabled=1
gpgcheck=1
repo_gpgcheck=1
gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
exclude=kube*
EOF

# Set SELinux in permissive mode (effectively disabling it)
setenforce 0
sed -i 's/SELINUX=enforcing$/SELINUX=disabled/' /etc/selinux/config

cat <<EOF >  /etc/sysctl.d/k8s.conf
net.bridge.bridge-nf-call-ip6tables = 1
net.bridge.bridge-nf-call-iptables = 1
net.ipv4.ip_forward = 1
EOF

# sysctl settings
cat <<EOF > /etc/modules-load.d/br_netfilter.conf
br_netfilter
EOF

sysctl --system

yum install -y kubelet kubeadm kubectl --disableexcludes=kubernetes

systemctl enable kubelet

# disable all swap
sed -i 's/\/dev\/mapper\/cl-swap/#\/dev\/mapper\/cl-swap/g' /etc/fstab
swapoff -a

# install crio
yum --enablerepo="base" -y install yum-utils
yum-config-manager --add-repo=https://cbs.centos.org/repos/paas7-crio-311-candidate/x86_64/os/
yum -y install --nogpgcheck cri-o

systemctl enable crio 
systemctl start crio

cat <<EOF > /etc/sysconfig/kubelet
KUBELET_EXTRA_ARGS=--cgroup-driver=systemd 
EOF
# if need cloud-controller manager add in kubelet args cloud-controller-manager --cloud-provider=external

systemctl daemon-reload
systemctl restart kubelet

# Create cluster with kubeadm

kubeadm init --pod-network-cidr=192.168.0.0/16

kubectl apply -f https://docs.projectcalico.org/v3.3/getting-started/kubernetes/installation/hosted/rbac-kdd.yaml
kubectl apply -f https://docs.projectcalico.org/v3.3/getting-started/kubernetes/installation/hosted/kubernetes-datastore/calico-networking/1.7/calico.yaml


mkdir -p $HOME/.kube
sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
sudo chown $(id -u):$(id -g) $HOME/.kube/config


#kubeadm token create --print-join-command

#kubeadm join 123.123.123.123:6443 --token sfvpos.byu8c2ls1pqrm3xa --discovery-token-ca-cert-hash sha256:466e7972a4b6997651ac1197fdde68d325a7bc41f2fccc2b1efc17515af61172


